ibexa.design_system_storybook.status:
    path: /storybook/status
    controller: 'Ibexa\Bundle\DesignSystemStorybook\Controller\StorybookController::getStatus'

ibexa.design_system_storybook.preview:
    path: /storybook/preview/{storybookId}
    controller: 'Ibexa\Bundle\DesignSystemStorybook\Controller\StorybookController::getPreview'
    requirements:
        storybookId: .+
