services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ibexa\Bundle\DesignSystemStorybook\Controller\StorybookController:
        tags:
            -   name: controller.service_arguments
