services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ibexa\DesignSystemStorybook\ComponentsResolver: ~

    Ibexa\DesignSystemStorybook\EventSubscriber\StorybookProfilerSubscriber:
        arguments:
            $profiler: '@?profiler'

    Ibexa\DesignSystemStorybook\Preview\PreviewViewBuilder: ~

    Ibexa\DesignSystemStorybook\Preview\TwigPreviewRenderer: ~

    Ibexa\DesignSystemStorybook\Preview\PreviewRendererInterface:
        alias: Ibexa\DesignSystemStorybook\Preview\TwigPreviewRenderer
