services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ibexa\DesignSystemStorybook\ComponentsResolver: ~

    Ibexa\DesignSystemStorybook\EventSubscriber\StorybookProfilerSubscriber:
        arguments:
            $profiler: '@?profiler'
